services:
  server:
    image: aklinker1/tic-tak-toe-server:dev
    environment: 
      DATABASE_URL: postgres://postgres:password@db:5432/tic-tak-toe-local
  db:
    image: postgres:alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tic-tak-toe-local
