---
swagger: '2.0'
info:
  version: 0.1.0
  title: Tic-Tak-Toe Server

produces:
  - application/json

paths:
  /health:
    get:
      operationId: checkHealth
      description: Check if the server is running
      responses:
        204:
          description: Server is up
  /games:
    post:
      operationId: startGame
      description: Start a new game
      responses:
        201:
          description: Game was started successfully
          schema:

definitions:
  Move:
    type: object
    properties:
      id:
        type: integer
        format: int64
      player:
        type: string
        enum: [p1, p2]


  Game:
    type: object
    default:
      size: 3
    properties:
      id:
        type: integer
        format: int64
        description: The id used to interact with a game
      size:
        type: integer
        description: The board size (n by n)
